### ISSUE TITLE
Reduce itkSegment901LTest memory usage

### ISSUE THREAD

**Issue by thewtex** [KitwareMedical/HASI#12]
CI tests are failing on Windows. Can we release memory when not used?

**Comment by tbirdso** [comment]
Adding details to this issue, I observed a little over 7GB RAM usage for this test running on Windows locally. It looks like GitHub Actions has a [7GB RAM limit for Windows](https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources).

Are there any performance benchmarks the `SegmentBonesInMicroCTFilter` needs to meet? If not, could we resolve the CI failure by using a slightly smaller mesh for test input?

**Comment by dzenanz** [comment]
We can totally use a smaller image, and that is on my TODO list. I will probably be able to get to that sometime next week.

**Comment by dzenanz** [comment]
Fixed by #36.
