### ISSUE TITLE
Create `hasi` package

### ISSUE THREAD

**Issue by thewtex** [KitwareMedical/HASI#33]
Create a `hasi` package that has the pure Python content, following the integration of #32 .

Organize the source into `src/hasi/` e.g. `src/hasi/hasi/__init__.py`, `src/hasi/pypackage.toml`. Initialize package configuration with [flit](https://pypi.org/project/flit/).

**Comment by tbirdso** [comment]
@thewtex Should KitwareMedical be set as author in package metadata? What email should be listed?

**Comment by thewtex** [comment]
@tbirdso please use my email: `matt.mccormick@kitware.com`.
