### ISSUE TITLE
CI fails to install Python 3.9 for `build-windows-python-packages` 

### ISSUE THREAD

**Issue by tbirdso** [KitwareMedical/HASI#45]
### Overview
CI checks are failing for `build-windows-python-packages (9)`. Github Actions fails to install pip with Python 3.9.

This issue recently emerged in at least one other external module as well and is not limited to HASI (see failure in [`ITKShape`](https://github.com/slicersalt/ITKShape/pull/17/checks?check_run_id=2301676630)).

Note that ".NET Framework" warnings predate this issue and are present in [previous successful builds](https://github.com/KitwareMedical/HASI/runs/2282210423).

## Expected behavior
Python versions install correctly. All CI checks succeed.

## Observed behavior
In "Install Python" step:
> Download https://gist.githubusercontent.com/jcfr/db7347e8708b9f32d45ab36125fad6d3/raw/8478d43e8f774c9602c78f9e81902792f923dd5c/get-pip.py
Installing pip using C:\Python39-x64\python.exe
Write-Error: This command cannot be run due to the error: The system cannot find the file specified.
Error: Process completed with exit code 1.

EDIT - CI log for failed check in `master` branch is here: [https://github.com/KitwareMedical/HASI/runs/2301754122](https://github.com/KitwareMedical/HASI/runs/2301754122)

Note that the CI check passed in the original pull request but failed in subsequent merge.

**Comment by dzenanz** [comment]
Due to
```text
Download python.org/ftp/python/3.9.4/python-3.9.4-amd64.exe
Found a python installation in a different directory [C:\hostedtoolcache\windows\Python\3.9.4\x64\] - Uninstalling
Installing C:\Downloads\python-3.9.0-amd64.exe into C:\Python39-x64\
```
we probably don't need to install python.

But the `Write-Error: This command cannot be run due to the error: The system cannot find the file specified.` probably comes from [install-python.ps1](https://raw.githubusercontent.com/scikit-build/scikit-ci-addons/master/windows/install-python.ps1), so https://github.com/scikit-build/scikit-ci-addons is the right place to resolve this bug. @jcfr do you agree?

**Comment by dzenanz** [comment]
Relevant CI log:
https://github.com/KitwareMedical/HASI/pull/40/checks?check_run_id=2300036875

**Comment by tbirdso** [comment]
Verified [check success](https://github.com/KitwareMedical/HASI/runs/2366534393).
