### ISSUE TITLE
CI Failures in `build-linux-python-packages`

### ISSUE THREAD

**Issue by tbirdso** [KitwareMedical/HASI#56]
## Overview

`build-linux-python-packages` checks for Python 3.6-3.9 are failing in `master`.

## Description

CI build script attempts to remove a DOxygen archive and fails. Could the archive location have changed in `dockcross-manylinux-download-cache-and-build-module-wheels.sh`?

Issue first appeared in [06167b](https://github.com/KitwareMedical/HASI/commit/06167bb7f78bded3fb91a6457591629c571a47f6) which made unrelated changes to pure-Python testing check.

## Expected behavior
No failures in CI.

## Observed behavior
> + rm dist/itk_boneenhancement-0.4.1-cp36-cp36m-linux_x86_64.whl
~/work/HASI/HASI
rm: cannot remove './ITKBoneEnhancement/doxygen-1.8.11.linux.bin.tar.gz': No such file or directory
Error: Process completed with exit code 1.

**Comment by dzenanz** [comment]
Maybe the docker image was updated? If so, looking there for [a change](https://github.com/dockcross/dockcross/commits/master) is probably the best.

**Comment by thewtex** [comment]
We can remove this line in the HASI CI configuration:

https://github.com/KitwareMedical/HASI/blob/88041b83975a77a4810f2f7c46f5b554afef5ada/.github/workflows/build-test-package.yml#L173

**Comment by tbirdso** [comment]
Were we originally removing archives due to space concerns? I believe this is also done in other external modules.

**Comment by dzenanz** [comment]
I think it was only done in HASI and Ultrasound.
